-- A small, hand-written multilingual catalogue for the demo's /languages page: the same kinds of products in
-- English, German, French, Spanish and Hungarian. Each language has its own index (lang_en ... lang_hu in
-- config/packages/fuzzphony.yaml) that stems and folds accents with that language's rules.
--
-- The rows are written so the page's presets have something to show: plural and inflected forms in some rows,
-- base forms in others, accented words, and phrases whose filler words are stop words.
-- Seeded once by docker/init.sh (only while the table does not exist).

CREATE TABLE lang_product (
    id          integer PRIMARY KEY,
    lang        text NOT NULL,
    name        text NOT NULL,
    description text NOT NULL,
    category    text NOT NULL
);

INSERT INTO lang_product (id, lang, name, description, category) VALUES
-- English
(1001, 'en', 'Cordless Drill 18V', 'Compact drill driver with two batteries, an LED work light and a 13 mm keyless chuck.', 'Tools'),
(1002, 'en', 'Hammer Drill 800W', 'Drills into brick and concrete; depth stop and side handle included.', 'Tools'),
(1003, 'en', 'Drill Bit Set, 35 pieces', 'Bits for wood, metal and masonry in a sturdy case.', 'Tools'),
(1004, 'en', 'Claw Hammer', 'Fibreglass handle with a non-slip grip, 500 g head.', 'Tools'),
(1005, 'en', 'Wireless Mouse', 'Quiet clicks, 18-month battery life and a nano USB receiver.', 'Computers'),
(1006, 'en', 'Gaming Mouse RGB', '16,000 DPI sensor, six programmable buttons and a braided cable.', 'Computers'),
(1007, 'en', 'Mouse Pad XL', 'Stitched edges and a non-slip rubber base, 90 × 40 cm.', 'Computers'),
(1008, 'en', 'Mechanical Keyboard', 'Hot-swappable switches and a detachable USB-C cable.', 'Computers'),
(1009, 'en', 'Laptop Stand', 'Aluminium stand that raises the screen to eye level.', 'Computers'),
(1010, 'en', 'Wireless Headphones', 'Over-ear, with noise cancelling and 30 hours of playback.', 'Audio'),
(1011, 'en', 'Bluetooth Speaker', 'Waterproof, 12 hours of music on one charge.', 'Audio'),
(1012, 'en', 'Trail Running Shoes', 'Grippy outsole and a cushioned midsole for long runs on rough ground.', 'Sports'),
(1013, 'en', 'Running Socks, 3 pairs', 'Padded heel and toe, breathable mesh.', 'Sports'),
(1014, 'en', 'Run Tracker Watch', 'GPS watch that records pace, distance and heart rate on every run.', 'Sports'),
(1015, 'en', 'Yoga Mat', '6 mm thick, non-slip, with a carrying strap.', 'Sports'),
(1016, 'en', 'Desk Lamp LED', 'Dimmable, with a flexible arm and warm-to-cool light.', 'Lighting'),
(1017, 'en', 'Arc Floor Lamp', 'Arched steel lamp on a marble base.', 'Lighting'),
(1018, 'en', 'Electric Kettle 1.7 L', 'Boils water in three minutes; stainless steel with a limescale filter.', 'Kitchen'),
(1019, 'en', 'Espresso Machine', '15-bar pump, steam wand and a cup-warming tray.', 'Kitchen'),
(1020, 'en', 'Café Espresso Cups, set of 4', 'Double-walled glass cups that keep coffee hot.', 'Kitchen'),
(1021, 'en', 'Crème Brûlée Torch', 'Refillable butane torch for caramelising sugar.', 'Kitchen'),
(1022, 'en', 'Chef''s Knife 20 cm', 'Forged steel, full tang and a balanced handle.', 'Kitchen'),
(1023, 'en', 'Bamboo Cutting Board', 'Reversible, with a groove that catches the juices.', 'Kitchen'),
(1024, 'en', 'Hand Blender', '600 W stick blender with whisk and chopper attachments.', 'Kitchen'),
(1025, 'en', 'Two-Person Camping Tent', 'Lightweight dome tent that goes up in five minutes.', 'Outdoor'),
(1026, 'en', 'Mummy Sleeping Bag', 'Comfortable down to −5 °C.', 'Outdoor'),
(1027, 'en', 'Hiking Backpack 40 L', 'Adjustable back system and a rain cover.', 'Outdoor'),
(1028, 'en', 'Garden Hose 25 m', 'Kink-free hose with a spray nozzle.', 'Garden'),
(1029, 'en', 'Pruning Shears', 'Bypass shears for branches up to 2 cm.', 'Garden'),
(1030, 'en', 'Watering Can 10 L', 'Galvanised steel with a brass rose.', 'Garden'),

-- German
(2001, 'de', 'Vogelhaus aus Holz', 'Wetterfestes Haus für Meisen und Spatzen, zum Aufhängen im Garten.', 'Garten'),
(2002, 'de', 'Modellbau-Häuser, 3er-Set', 'Drei Häuser im Maßstab 1:87 für die Modelleisenbahn.', 'Spielwaren'),
(2003, 'de', 'Rauchmelder', 'Schützt Haus und Wohnung, mit 10-Jahres-Batterie.', 'Sicherheit'),
(2004, 'de', 'Kabellose Maus', 'Leise Tasten, USB-Empfänger und 18 Monate Laufzeit.', 'Computer'),
(2005, 'de', 'Ergonomische Maus', 'Vertikale Form, die das Handgelenk entlastet.', 'Computer'),
(2006, 'de', 'Mauspad XL', 'Rutschfeste Unterseite und vernähte Ränder, 90 × 40 cm.', 'Computer'),
(2007, 'de', 'Buch „Brot backen für Einsteiger“', '60 Rezepte vom Sauerteig bis zum Baguette.', 'Medien'),
(2008, 'de', 'Buch „Gemüse aus dem eigenen Garten“', 'Anbauen, pflegen, ernten: ein Jahr im Gemüsebeet.', 'Medien'),
(2009, 'de', 'Leselampe mit Klemme', 'Klemmleuchte für Bücher und Notenständer, drei Helligkeitsstufen.', 'Beleuchtung'),
(2010, 'de', 'Schreibtischlampe LED', 'Dimmbar, mit flexiblem Arm.', 'Beleuchtung'),
(2011, 'de', 'Laptop-Tasche aus Filz', 'Gepolsterte Hülle für Geräte bis 14 Zoll, mit Reißverschluss.', 'Taschen'),
(2012, 'de', 'Wanderrucksack 25 L', 'Leicht, mit Fach für das Trinksystem.', 'Outdoor'),
(2013, 'de', 'Kaffeemaschine mit Thermoskanne', 'Brüht bis zu acht Tassen und hält den Kaffee zwei Stunden heiß.', 'Küche'),
(2014, 'de', 'Wasserkocher 1,7 L', 'Edelstahl, Kalkfilter und automatische Abschaltung.', 'Küche'),
(2015, 'de', 'Gewürzmühle aus Keramik', 'Für Salz und Pfeffer, stufenlos einstellbar.', 'Küche'),
(2016, 'de', 'Brotkasten aus Bambus', 'Hält Brot länger frisch, mit Schneidebrett im Deckel.', 'Küche'),
(2017, 'de', 'Kühlbox 24 Liter', 'Elektrisch, für Auto und Camping, 12 V und 230 V.', 'Outdoor'),
(2018, 'de', 'Mini-Kühlschrank', '45 Liter für Büro oder Wohnmobil, fast lautlos.', 'Haushalt'),
(2019, 'de', 'Staubsauger ohne Beutel', 'Zyklon-Technik und waschbarer HEPA-Filter.', 'Haushalt'),
(2020, 'de', 'Dampfbügeleisen', '2400 W, Keramiksohle und Tropf-Stopp.', 'Haushalt'),
(2021, 'de', 'Akku-Bohrschrauber 18 V', 'Zwei Akkus, LED-Licht und Schnellspannbohrfutter.', 'Werkzeug'),
(2022, 'de', 'Hammer mit Fiberglasstiel', '500 g, rutschfester Griff.', 'Werkzeug'),
(2023, 'de', 'Gartenschlauch 25 m', 'Knickfest, mit Sprühdüse.', 'Garten'),
(2024, 'de', 'Rosenschere', 'Für Äste bis 2 cm, mit Sicherheitsverschluss.', 'Garten'),
(2025, 'de', 'Gießkanne 10 L', 'Verzinkter Stahl, Brause aus Messing.', 'Garten'),
(2026, 'de', 'Zelt für zwei Personen', 'Leichtes Kuppelzelt, in fünf Minuten aufgebaut.', 'Outdoor'),
(2027, 'de', 'Mumienschlafsack', 'Komfortbereich bis −5 °C.', 'Outdoor'),
(2028, 'de', 'Trail-Laufschuhe', 'Griffige Sohle für lange Läufe im Gelände.', 'Sport'),
(2029, 'de', 'Yogamatte', '6 mm dick, rutschfest, mit Tragegurt.', 'Sport'),
(2030, 'de', 'Kabellose Kopfhörer', 'Geräuschunterdrückung und 30 Stunden Wiedergabe.', 'Audio'),

-- French
(3001, 'fr', 'Cheval à bascule en bois', 'Jouet traditionnel en hêtre massif, dès 2 ans.', 'Jouets'),
(3002, 'fr', 'Figurines chevaux de ferme, lot de 6', 'Chevaux peints à la main, avec un enclos.', 'Jouets'),
(3003, 'fr', 'Livre « Soigner son cheval »', 'Guide pratique, de l''alimentation au pansage.', 'Livres'),
(3004, 'fr', 'Crème hydratante visage', 'Texture légère à l''aloe vera, 50 ml.', 'Beauté'),
(3005, 'fr', 'Crème solaire SPF 50', 'Résistante à l''eau, sans parfum.', 'Beauté'),
(3006, 'fr', 'Chalumeau à crème brûlée', 'Rechargeable, flamme réglable pour caraméliser le sucre.', 'Cuisine'),
(3007, 'fr', 'Coffret de crèmes pour les mains', 'Trois crèmes au karité, à la lavande et au citron.', 'Beauté'),
(3008, 'fr', 'Aspirateur sans fil', 'Autonomie de 40 minutes, filtre lavable.', 'Maison'),
(3009, 'fr', 'Fer à repasser vapeur', '2400 W, semelle en céramique.', 'Maison'),
(3010, 'fr', 'Machine à café à capsules', 'Pression de 19 bars, réservoir d''un litre.', 'Cuisine'),
(3011, 'fr', 'Bouilloire électrique 1,7 L', 'Inox, arrêt automatique et filtre anticalcaire.', 'Cuisine'),
(3012, 'fr', 'Théière en fonte', 'Style japonais, 0,8 litre, avec infuseur.', 'Cuisine'),
(3013, 'fr', 'Couteau de chef 20 cm', 'Acier forgé, manche équilibré.', 'Cuisine'),
(3014, 'fr', 'Planche à découper en bambou', 'Réversible, avec une rigole pour le jus.', 'Cuisine'),
(3015, 'fr', 'Sac à dos pour vélo', 'Imperméable, se fixe en un geste sur le porte-bagages.', 'Vélo'),
(3016, 'fr', 'Vélo pliant 20 pouces', 'Cadre en aluminium, sept vitesses.', 'Vélo'),
(3017, 'fr', 'Casque de vélo', 'Ventilé, avec un éclairage arrière intégré.', 'Vélo'),
(3018, 'fr', 'Chapeau de paille', 'Tressé à la main, ruban en coton.', 'Mode'),
(3019, 'fr', 'Écharpe en laine', 'Laine mérinos, 180 × 30 cm.', 'Mode'),
(3020, 'fr', 'Souris sans fil', 'Clics silencieux et récepteur USB.', 'Informatique'),
(3021, 'fr', 'Clavier mécanique', 'Touches rétroéclairées, disposition AZERTY.', 'Informatique'),
(3022, 'fr', 'Lampe de bureau LED', 'Bras articulé, trois températures de couleur.', 'Luminaires'),
(3023, 'fr', 'Écouteurs sans fil', 'Réduction de bruit, 24 heures d''autonomie avec l''étui.', 'Audio'),
(3024, 'fr', 'Enceinte Bluetooth', 'Étanche, 12 heures d''écoute.', 'Audio'),
(3025, 'fr', 'Tente pour deux personnes', 'Montée en cinq minutes, 2,1 kg.', 'Plein air'),
(3026, 'fr', 'Sac de couchage', 'Confort jusqu''à −5 °C.', 'Plein air'),
(3027, 'fr', 'Arrosoir 10 litres', 'Acier galvanisé, pomme en laiton.', 'Jardin'),
(3028, 'fr', 'Sécateur', 'Pour les branches jusqu''à 2 cm.', 'Jardin'),
(3029, 'fr', 'Tuyau d''arrosage 25 m', 'Anti-torsion, avec pistolet.', 'Jardin'),
(3030, 'fr', 'Tapis de yoga', '6 mm, antidérapant, avec sangle de transport.', 'Sport'),

-- Spanish
(4001, 'es', 'Cancionero infantil', 'Cien canciones populares con acordes para guitarra.', 'Libros'),
(4002, 'es', 'Altavoz Bluetooth', 'Resistente al agua: tus canciones favoritas durante 12 horas.', 'Audio'),
(4003, 'es', 'Caja de música de madera', 'Suena una canción de cuna al abrir la tapa.', 'Juguetes'),
(4004, 'es', 'Auriculares inalámbricos', 'Cancelación de ruido y 30 horas de batería.', 'Audio'),
(4005, 'es', 'Lámpara de escritorio LED', 'Brazo flexible y luz regulable.', 'Iluminación'),
(4006, 'es', 'Lámpara de pie', 'Base de mármol y pantalla de lino.', 'Iluminación'),
(4007, 'es', 'Lámparas solares de jardín, pack de 6', 'Se encienden solas al anochecer.', 'Jardín'),
(4008, 'es', 'Café molido de Colombia', 'Tueste medio, paquete de 500 g.', 'Alimentación'),
(4009, 'es', 'Cafetera italiana', 'Aluminio, seis tazas, apta para gas.', 'Cocina'),
(4010, 'es', 'Hervidor eléctrico 1,7 L', 'Acero inoxidable y apagado automático.', 'Cocina'),
(4011, 'es', 'Sartén antiadherente 28 cm', 'Apta para inducción, mango de baquelita.', 'Cocina'),
(4012, 'es', 'Cuchillo de chef 20 cm', 'Acero forjado y mango equilibrado.', 'Cocina'),
(4013, 'es', 'Tabla de cortar de bambú', 'Reversible, con canal para los jugos.', 'Cocina'),
(4014, 'es', 'Funda de silicona para móvil', 'Protege las esquinas y no amarillea.', 'Accesorios'),
(4015, 'es', 'Bicicleta plegable', 'Cuadro de aluminio y siete velocidades.', 'Bicicletas'),
(4016, 'es', 'Casco de bicicleta', 'Ventilado, con luz trasera integrada.', 'Bicicletas'),
(4017, 'es', 'Ratón inalámbrico', 'Clics silenciosos y receptor USB.', 'Informática'),
(4018, 'es', 'Teclado mecánico', 'Teclas retroiluminadas, distribución española con ñ.', 'Informática'),
(4019, 'es', 'Tienda de campaña para dos', 'Se monta en cinco minutos, 2,1 kg.', 'Aire libre'),
(4020, 'es', 'Saco de dormir', 'Temperatura de confort hasta −5 °C.', 'Aire libre'),
(4021, 'es', 'Mochila de senderismo 40 L', 'Espalda ajustable y funda para la lluvia.', 'Aire libre'),
(4022, 'es', 'Regadera de 10 litros', 'Acero galvanizado, alcachofa de latón.', 'Jardín'),
(4023, 'es', 'Manguera de jardín 25 m', 'Antitorsión, con pistola de riego.', 'Jardín'),
(4024, 'es', 'Tijeras de podar', 'Para ramas de hasta 2 cm.', 'Jardín'),
(4025, 'es', 'Esterilla de yoga', '6 mm, antideslizante, con correa.', 'Deporte'),
(4026, 'es', 'Zapatillas de trail', 'Suela amortiguada para tiradas largas por el monte.', 'Deporte'),
(4027, 'es', 'Aspiradora sin cable', '40 minutos de autonomía y filtro lavable.', 'Hogar'),
(4028, 'es', 'Plancha de vapor', '2400 W, suela cerámica.', 'Hogar'),
(4029, 'es', 'Juego de sábanas de algodón', 'Para cama de 150, percal de 200 hilos.', 'Hogar'),
(4030, 'es', 'Mantel de lino', 'Rectangular, 150 × 250 cm.', 'Hogar'),

-- Hungarian
(5001, 'hu', 'Ház alakú fali polc', 'Fenyőfa polc gyerekszobába, két kis rekesszel.', 'Lakberendezés'),
(5002, 'hu', 'Madáretető', 'Kis ház cinegéknek és verebeknek, fára akasztható.', 'Kert'),
(5003, 'hu', 'Makett házak, 3 darabos', 'Három épület a vasútmodellhez, 1:87 méretarányban.', 'Játék'),
(5004, 'hu', 'Füstérzékelő', 'Tíz évig működik egyetlen elemmel.', 'Biztonság'),
(5005, 'hu', 'Könyv: A magyar konyha', 'Száz klasszikus recept a gulyástól a rétesig.', 'Média'),
(5006, 'hu', 'Könyv: Kertészkedés kezdőknek', 'Vetés, ápolás, betakarítás egész évben.', 'Média'),
(5007, 'hu', 'Olvasólámpa csipesszel', 'Könyvek és kották olvasásához, három fényerővel.', 'Világítás'),
(5008, 'hu', 'Asztali lámpa LED', 'Szabályozható fényerő, hajlítható kar.', 'Világítás'),
(5009, 'hu', 'Vezeték nélküli egér', 'Halk kattintás és USB-vevő.', 'Számítástechnika'),
(5010, 'hu', 'Gamer egér RGB', '16 000 DPI, hat programozható gomb.', 'Számítástechnika'),
(5011, 'hu', 'Egérpad XL', 'Csúszásmentes alj, 90 × 40 cm.', 'Számítástechnika'),
(5012, 'hu', 'Mechanikus billentyűzet', 'Cserélhető kapcsolók, levehető USB-C kábel.', 'Számítástechnika'),
(5013, 'hu', 'Kávéfőző termoszkannával', 'Nyolc csésze kávé, amely két órán át forró marad.', 'Konyha'),
(5014, 'hu', 'Vízforraló 1,7 l', 'Rozsdamentes acél, vízkőszűrő, automatikus kikapcsolás.', 'Konyha'),
(5015, 'hu', 'Kenyérpirító', 'Két szelet, hét fokozat, kihúzható morzsatálca.', 'Konyha'),
(5016, 'hu', 'Evőeszközkészlet', 'Kés, villa és kanál hat személyre, rozsdamentes acélból.', 'Konyha'),
(5017, 'hu', 'Fűszerőrlő', 'Sóhoz és borshoz, kerámia őrlővel, fokozatmentesen állítható.', 'Konyha'),
(5018, 'hu', 'Laptoptáska filcből', 'Párnázott tok 14 colos gépekhez, cipzárral.', 'Táskák'),
(5019, 'hu', 'Porszívó zsák nélkül', 'Ciklon technológia és mosható HEPA-szűrő.', 'Háztartás'),
(5020, 'hu', 'Gőzölős vasaló', '2400 W, kerámia talp.', 'Háztartás'),
(5021, 'hu', 'Akkus fúró-csavarozó 18 V', 'Két akkumulátor és LED-lámpa.', 'Szerszámok'),
(5022, 'hu', 'Kalapács üvegszálas nyéllel', '500 g, csúszásmentes markolat.', 'Szerszámok'),
(5023, 'hu', 'Kerti slag 25 m', 'Megtörésmentes, szórófejjel.', 'Kert'),
(5024, 'hu', 'Metszőolló', '2 cm-es ágakig, biztonsági zárral.', 'Kert'),
(5025, 'hu', 'Locsolókanna 10 l', 'Horganyzott acél, sárgaréz rózsa.', 'Kert'),
(5026, 'hu', 'Kétszemélyes sátor', 'Könnyű kupolasátor, öt perc alatt felállítható.', 'Szabadidő'),
(5027, 'hu', 'Hálózsák', 'Komfort hőmérséklet −5 °C-ig.', 'Szabadidő'),
(5028, 'hu', 'Túrahátizsák 40 l', 'Állítható hátrész, esővédő huzattal.', 'Szabadidő'),
(5029, 'hu', 'Terepfutó cipő', 'Tapadós talp a hosszú futásokhoz.', 'Sport'),
(5030, 'hu', 'Vezeték nélküli fejhallgató', 'Zajszűrés és 30 óra üzemidő.', 'Audio');
